version: "3.3"

volumes:
  homedir:

services:

  dayzserver:
    build: .
    ports:
      - "2302:2302/udp"
      - "27016:27016/udp"
    volumes:
      - homedir:/home/user
      - ./files:/files
    environment:
#     Don't use double quotes. Escape any forward slashes: SERVERNAME=My thing \/ My other thing
      - SERVERNAME=DayZ on Linux for Linux
#     Set your own RCON password. Otherwise, a random one will be generated and shown in the log on the first run.
#      - RCON_PASSWORD=H4CKM3