version: "3.3"

volumes:
  homedir:

services:

  main:
    build: .
    ports:
      - "2302:2302/udp"
      - "27016:27016/udp"
    volumes:
      - homedir:/home/user
      - ./files:/files
#    environment:
#      # So we don't have to always download the full server when testing
#      - FAKE_DAYZ_INSTALL=1