version: "3.3"

volumes:
  homedir:

services:

  main:
    build: .
    command: bash -c "/files/dayzserver start"
    ports:
      - "2302:2302/udp"
      - "2303:2303/udp"
      - "2304:2304/udp"
      - "27016:27016/udp"
    volumes:
      - homedir:/home/user
      - ./files:/files
