version: "3.3"

volumes:
  homedir:

services:

  config:
    build: .
    command: /files/login.sh
    volumes:
      - homedir:/home/user
      - ./files:/files

  dayzserver:
    build: .
    ports:
      - "2302:2302/udp"
      - "27016:27016/udp"
    volumes:
      - homedir:/home/user
      - ./files:/files